export const skills = {
  heading: 'Skills',
  quote: 'Build your skills, not your resume',
  techSkills: [
    'C',
    'C++',
    'Java',
    'JavaScript',
    'NodeJS',
    'ReactJS',
    'HTML',
    'CSS',
    'Bootstrap',
    'Material Design',
    'Git',
    'GitHub',
    'MongoDB',
  ],
  interpersonalSkills: ['Teaching', 'Time Management'],
}
